name: Go MPV Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version:
          - 1.22.x # newest
          - 1.21.x
          - 1.20.x
          - 1.19.x # debian stable
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: |
          if [[ $RUNNER_OS == 'Linux' ]]; then
            sudo apt-get install -y libmpv-dev
          elif [[ $RUNNER_OS == 'macOS' ]]; then
            brew install mpv
            
            # Export Homebrew's paths (macOS)
            echo "C_INCLUDE_PATH=/usr/local/include:/opt/homebrew/include:$C_INCLUDE_PATH" >> $GITHUB_ENV
            echo "LIBRARY_PATH=/usr/local/lib:/opt/homebrew/lib:$LIBRARY_PATH" >> $GITHUB_ENV
            echo "CGO_CFLAGS=-I/usr/local/include -I/opt/homebrew/include" >> $GITHUB_ENV
            echo "CGO_LDFLAGS=-L/usr/local/lib -L/opt/homebrew/lib" >> $GITHUB_ENV
          fi
          go mod download

      - name: Run tests
        run: go test -v ./...
